apiVersion: apps/v1
kind: Deployment
metadata:
  name: seg-api
  labels:
    app: seg-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seg-api
  template:
    metadata:
      labels:
        app: seg-api
    spec:
      containers:
        - name: seg-api
          image: seg-api:local          # uses your local Docker image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
