apiVersion: apps/v1
kind: Deployment
metadata:
  name: seg-api
  labels:
    app: seg-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seg-api
  template:
    metadata:
      labels:
        app: seg-api
    spec:
      containers:
        - name: seg-api
          image: ghcr.io/atharva2901/real-time-segmentation:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
