name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write   # allow pushing to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/atharva2901/real-time-segmentation:${{ github.sha }}
            ghcr.io/atharva2901/real-time-segmentation:main

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.32.2"

      - name: Write kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Rollout new image
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          kubectl set image deployment/seg-api seg-api=ghcr.io/atharva2901/real-time-segmentation:${{ github.sha }}
          kubectl rollout status deployment/seg-api
